In [12]:
# List Imports 
import numpy as np
import pandas as pd
from datetime import datetime as dt
import os
import glob
from pathlib import Path

In [13]:
DATA = os.path.realpath('../data/football_uk_data/')
print(DATA)

file_path = Path(os.path.realpath('../data/football_uk_data/'))

C:\Users\ntlg4\PycharmProjects\laliga\data\football_uk_data

In [14]:
files = []
for file in os.listdir(DATA):
    files.append(os.path.join(file_path, file))

In [15]:
match_data = pd.concat([pd.read_csv(file) for file in files],axis = 0).reset_index(drop=True)

In [16]:
match_data

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,SP1,09/09/00,Barcelona,Malaga,2.0,1.0,H,2.0,0.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,09/09/00,La Coruna,Ath Bilbao,2.0,0.0,H,0.0,0.0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,09/09/00,Real Madrid,Valencia,2.0,1.0,H,0.0,0.0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,09/09/00,Sociedad,Santander,2.0,2.0,D,0.0,0.0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,09/09/00,Zaragoza,Espanol,1.0,2.0,A,0.0,0.0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18522,SP2,29/05/2022,Leganes,Almeria,2.0,2.0,D,2.0,1.0,H,...,1.84,0.75,1.77,2.10,1.83,2.09,1.88,2.12,1.82,2.03
18523,SP2,29/05/2022,Oviedo,Ibiza,3.0,2.0,H,1.0,0.0,H,...,2.03,-1.00,1.77,2.10,1.81,2.11,1.90,2.17,1.82,2.02
18524,SP2,29/05/2022,Sp Gijon,Las Palmas,0.0,1.0,A,0.0,1.0,A,...,1.75,0.25,1.95,1.90,2.01,1.89,2.12,1.96,2.00,1.85
18525,SP2,29/05/2022,Tenerife,Cartagena,1.0,2.0,A,0.0,2.0,A,...,2.08,-0.50,1.98,1.88,1.99,1.92,2.03,2.02,1.91,1.92
18526,SP2,29/05/2022,Valladolid,Huesca,3.0,0.0,H,0.0,0.0,D,...,2.72,-1.50,2.02,1.83,2.04,1.87,2.08,1.92,2.01,1.83

In [ ]:
match_data.iloc[:, :22]

In [7]:
match_data['Date'].min().date()

TypeError: '<=' not supported between instances of 'str' and 'float'